/**
 * The word lists behind the readability checks.
 *
 * Kept apart from the analyser so the analyser reads as an algorithm rather
 * than as data, and so the tables can be extended without touching it.
 */

/**
 * Words ending in "ly" that are not adverbs.
 *
 * Without this, "family", "reply", "supply" and every "Italy" get flagged, and
 * a rule that fires on obvious non-adverbs gets switched off by the second day.
 *
 * Adverbs that merely *look* harmless — "actually", "reportedly", "simply" —
 * are deliberately absent: Hemingway flags them, and they are the ones worth
 * flagging.
 */
export const NON_ADVERBS = new Set([
  "ally", "anomaly", "apply", "assembly", "belly", "bubbly", "bully",
  "comply", "costly", "curly", "daily", "dastardly", "deadly", "doily",
  "early", "elderly", "family", "folly", "friendly", "ghastly", "giggly",
  "gully", "heavenly", "hillbilly", "holy", "homely", "homily", "hourly",
  "imply", "italy", "jelly", "jolly", "july", "kindly", "lively", "lonely",
  "lovely", "lowly", "melancholy", "monopoly", "monthly", "multiply",
  "nightly", "oily", "only", "panoply", "pearly", "ply", "quarterly",
  "rally", "rely", "reply", "silly", "smelly", "spindly", "supply", "surly",
  "timely", "ugly", "underbelly", "weekly", "wily", "wobbly", "wooly",
  "worldly", "wrinkly", "yearly",
]);

/**
 * Hedges and intensifiers. Hemingway highlights these beside adverbs because
 * they weaken a sentence the same way.
 */
export const QUALIFIERS: string[] = [
  "a bit", "a little", "a lot of", "almost", "arguably", "at all",
  "basically", "essentially", "fairly", "in my opinion", "i believe",
  "i feel", "i think", "just", "kind of", "maybe", "more or less",
  "perhaps", "pretty much", "quite", "rather", "really", "seems to",
  "somewhat", "sort of", "very",
];

/** Past participles a "-ed" test cannot catch. */
export const IRREGULAR_PARTICIPLES = new Set([
  "awoken", "beaten", "become", "been", "begun", "bent", "beset", "bet",
  "bid", "bitten", "bled", "blown", "born", "bought", "bound", "bred",
  "broadcast", "broken", "brought", "built", "burnt", "burst", "cast",
  "caught", "chosen", "clung", "come", "cost", "crept", "cut", "dealt",
  "dived", "done", "drawn", "driven", "drunk", "eaten", "fallen", "fed",
  "felt", "fit", "fled", "flown", "flung", "forbidden", "forgiven",
  "forgotten", "forsaken", "fought", "found", "frozen", "given", "gone",
  "gotten", "ground", "grown", "hidden", "held", "hung", "hurt", "kept",
  "knelt", "knit", "known", "laid", "lain", "leapt", "learnt", "led",
  "left", "lent", "let", "lit", "lost", "made", "meant", "met", "misspelt",
  "mistaken", "mown", "overcome", "overdone", "overtaken", "overthrown",
  "paid", "pled", "proven", "put", "quit", "read", "rid", "ridden", "risen",
  "run", "rung", "said", "sat", "sawn", "seen", "sent", "set", "sewn",
  "shaken", "shaven", "shed", "shod", "shone", "shorn", "shot", "shown",
  "shrunk", "shut", "slain", "slept", "slid", "slit", "slung", "smitten",
  "sold", "sought", "sown", "spent", "spilt", "spit", "split", "spoken",
  "spread", "sprung", "spun", "stolen", "stood", "strewn", "stridden",
  "struck", "strung", "stuck", "stung", "stunk", "sung", "sunk", "swept",
  "swollen", "sworn", "swum", "swung", "taken", "taught", "thought",
  "thrown", "thrust", "told", "torn", "trodden", "understood", "upheld",
  "upset", "wed", "wept", "withheld", "withstood", "woken", "won", "worn",
  "wound", "woven", "written", "wrung",
]);

export const BE_VERBS = ["is", "are", "was", "were", "be", "been", "being", "am", "get", "gets", "got"];

/**
 * Phrases with a shorter equivalent. Hemingway's purple highlight.
 *
 * Longest phrases first at match time, so "a number of" wins over "number".
 */
export const COMPLEX_PHRASES: Record<string, string[]> = {
  "a large number of": ["many"],
  "a majority of": ["most"],
  "a number of": ["many", "some"],
  "a small number of": ["a few"],
  "along the lines of": ["like"],
  "an innumerable number of": ["countless"],
  "as a matter of fact": ["in fact"],
  "as a means of": ["to"],
  "as of yet": ["yet"],
  "as to": ["about"],
  "at the present time": ["now"],
  "at this point in time": ["now"],
  "based on the fact that": ["because"],
  "be able to": ["can"],
  "by means of": ["by"],
  "come to a conclusion": ["conclude"],
  "despite the fact that": ["although"],
  "due to the fact that": ["because"],
  "during the course of": ["during"],
  "for the purpose of": ["to"],
  "for the reason that": ["because"],
  "give rise to": ["cause"],
  "has the ability to": ["can"],
  "has the capacity to": ["can"],
  "have a tendency to": ["tend to"],
  "in a manner similar to": ["like"],
  "in a timely manner": ["promptly"],
  "in close proximity to": ["near"],
  "in excess of": ["more than"],
  "in light of the fact that": ["because"],
  "in order to": ["to"],
  "in regard to": ["about"],
  "in spite of the fact that": ["although"],
  "in the amount of": ["for"],
  "in the event that": ["if"],
  "in the near future": ["soon"],
  "in the vicinity of": ["near"],
  "is able to": ["can"],
  "it is often the case that": ["often"],
  "it is possible that": ["possibly"],
  "make a decision": ["decide"],
  "make an assumption": ["assume"],
  "notwithstanding the fact that": ["although"],
  "on a daily basis": ["daily"],
  "on account of": ["because"],
  "on the grounds that": ["because"],
  "on the occasion of": ["when"],
  "owing to the fact that": ["because"],
  "prior to": ["before"],
  "provided that": ["if"],
  "put an end to": ["end"],
  "referred to as": ["called"],
  "subsequent to": ["after"],
  "take into consideration": ["consider"],
  "the fact that": ["that"],
  "the majority of": ["most"],
  "the question as to whether": ["whether"],
  "there is no doubt that": ["doubtless"],
  "until such time as": ["until"],
  "with reference to": ["about"],
  "with regard to": ["about"],
  "with the exception of": ["except"],
  "abundance": ["plenty", "enough"],
  "accelerate": ["speed up"],
  "accentuate": ["stress"],
  "accompany": ["go with", "with"],
  "accomplish": ["do", "finish"],
  "accordingly": ["so"],
  "additional": ["more", "extra"],
  "advantageous": ["helpful"],
  "aforementioned": ["said"],
  "aggregate": ["total"],
  "alleviate": ["ease", "reduce"],
  "allocate": ["divide", "assign"],
  "alternatively": ["or"],
  "ameliorate": ["improve", "help"],
  "anticipate": ["expect"],
  "apparent": ["clear", "plain"],
  "appreciable": ["many"],
  "ascertain": ["find out", "learn"],
  "attain": ["meet"],
  "attributable to": ["because of"],
  "authorize": ["allow", "let"],
  "cease": ["stop"],
  "circumvent": ["avoid", "get around"],
  "cognizant": ["aware"],
  "commence": ["begin", "start"],
  "compensate": ["pay"],
  "component": ["part"],
  "comprise": ["form", "include"],
  "conceal": ["hide"],
  "concerning": ["about", "on"],
  "consequently": ["so"],
  "constitutes": ["is", "forms"],
  "demonstrate": ["prove", "show"],
  "depart": ["leave", "go"],
  "designate": ["choose", "name"],
  "discontinue": ["drop", "stop"],
  "disseminate": ["send", "spread"],
  "eliminate": ["cut", "drop", "end"],
  "elucidate": ["explain"],
  "employ": ["use"],
  "endeavor": ["try"],
  "enumerate": ["count"],
  "equitable": ["fair"],
  "equivalent": ["equal"],
  "evaluate": ["test", "check"],
  "evidenced": ["showed"],
  "exclusively": ["only"],
  "expedite": ["hurry", "speed up"],
  "expend": ["spend"],
  "facilitate": ["ease", "help"],
  "finalize": ["complete", "finish"],
  "frequently": ["often"],
  "furnish": ["give", "send"],
  "however": ["but", "yet"],
  "identical": ["same"],
  "illustrate": ["show", "explain"],
  "impacted": ["affected", "changed"],
  "implement": ["install", "put in place"],
  "indicate": ["show", "say"],
  "initiate": ["start", "begin"],
  "insufficient": ["not enough"],
  "modify": ["change"],
  "monitor": ["check", "watch"],
  "necessitate": ["cause", "need"],
  "nevertheless": ["still", "but"],
  "numerous": ["many"],
  "objective": ["aim", "goal"],
  "obligate": ["bind", "compel"],
  "obtain": ["get"],
  "utilize": ["use"],
  "utilization": ["use"],
  "validate": ["confirm"],
  "verify": ["check", "prove"],
  "whereas": ["but", "while"],
  "additionally": ["also", "and"],
  "approximately": ["about"],
  "commensurate": ["equal", "matching"],
  "endeavour": ["try"],
  "inquire": ["ask"],
  "moreover": ["also", "besides"],
  "notify": ["tell"],
  "numerous times": ["often"],
  "participate": ["take part"],
  "portion": ["part"],
  "possess": ["have", "own"],
  "previous": ["earlier", "prior"],
  "purchase": ["buy"],
  "regarding": ["about", "on"],
  "relocate": ["move"],
  "remainder": ["rest"],
  "represents": ["is"],
  "request": ["ask"],
  "require": ["need"],
  "reside": ["live"],
  "residence": ["home"],
  "retain": ["keep"],
  "solicit": ["ask for", "request"],
  "state-of-the-art": ["latest"],
  "subsequently": ["later", "then"],
  "sufficient": ["enough"],
  "terminate": ["end", "stop"],
  "therefore": ["so"],
  "transmit": ["send"],
  "transpire": ["happen"],
  "ultimate": ["last", "final"],
  "undertake": ["do", "try"],
};

/** Longest-first, so multi-word phrases beat the single words inside them. */
export const COMPLEX_PHRASE_KEYS = Object.keys(COMPLEX_PHRASES).sort(
  (a, b) => b.length - a.length,
);
